---
name: Freddy Ray Drennan
address: "812 Cameron Drive, Severance, CO 80550"
www: ndexr.com
phone: +1 254 931 8313
email: "drennanfreddy@gmail.com"
github: fdrennan
linkedin: freddydrennan
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: "000088"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(vitae)
source("baretable.R")
```


$$
\\
\\
$$
Dear Hiring Manager,

I am a multi-language, Agile data scientist with substantial knowledge in data architecture and optimization methods, an overwhelming git commit history, and love for infrastructure from the origination of data to the final interpretation and presentation of it. Before data science, I was an Army trauma nurse in a Forward Surgical Team working in Afghanistan at the height of the war. I frequently speak at meetups, teach junior data scientists about best practices, work within a production environment.

This position is of particular interest to me because I built the optimization platform for Adtaxi - Quantum, Omnichannel, and search pacing. Omnichannel is a large, dynamically buily linear program set to optimize cross channel between Adwords, Facebook, and The Trade Desk holding multiple factors consistent like overall retail budget, margins, and minimum budgets. I unified the language of these platforms into their common pieces and dropped the optimization configuration time from three days in Excel to a 15 minute web based service.

I appreciate your time and hope to hear from you soon. 

Freddy